class CreateComments < ActiveRecord::Migration
  def change
    create_table :comments do |t|
      t.string :commenter
      t.text :body
      t.references :article, index: true, foreign_key: true

      t.timestamps null: false
    end
  end
end

# migration generated by using "bin/rails generate model Comment commenter:string body:text article:references"
# run "bin/rake db:migrate" to migrate to the database
